import = [
    "~/.config/alacritty/themes/themes/nord.toml"
]

[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
opacity = 0.45
title = "Alacritty"

[window.dimensions]
columns = 105
lines = 30
