[colors.primary]
background = '0xb5d8f6'
foreground = '0x2a343a'

[colors.normal]
black =   '0x232c31'
red =     '0x2a5491'
green =   '0x237986'
yellow =  '0xa03b1e'
blue =    '0x484d79'
magenta = '0xc59820'
cyan =    '0xb02f30'
white =   '0x9ea7a6'

[colors.bright]
black =   '0x3f4944'
red =     '0x2a5491'
green =   '0x237986'
yellow =  '0xa03b1e'
blue =    '0x484d79'
magenta = '0xc59820'
cyan =    '0xb02f30'
white =   '0xb5d8f6'

