#TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#1a1b26' #orig
#background = '#1a1a1a'
#background = '#2e2e2e'
foreground = '#c0caf5'
#foreground = '#a9b1d6'

[colors.cursor]
cursor = '#c0caf5'
text = '#1a1b26'

# Normal colors
[colors.normal]
black=   '#32344a'
red=     '#f7768e'
green=   '#9ece6a'
yellow=  '#e0af68'
blue=    '#7aa2f7'
magenta= '#ad8ee6'
cyan=    '#449dab'
white=   '#787c99'

# Bright colors
[colors.bright]
black=   '#444b6a'
red=     '#ff7a93'
green=   '#b9f27c'
yellow=  '#ff9e64'
blue=    '#7da6ff'
magenta= '#bb9af7'
cyan=    '#0db9d7'
white=   '#acb0d0'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#15161e'

[[colors.indexed_colors]]
index = 17
color = '#414868'

[font]
size = 12.0

[font.normal]
family = "Ubuntu mono"

[window]
opacity = 0.75
title = "Alacritty"

[window.dimensions]
columns = 105
lines = 30
